apiVersion: container.gcp.zicong.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    initialNodeCount: 1
    location: us-central1
    removeDefaultNodePool: true

---

apiVersion: container.gcp.zicong.io/v1beta1
kind: NodePool
metadata:
  annotations:
    meta.upbound.io/example-id: container/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: primary_preemptible_nodes
  name: primary-preemptible-nodes
spec:
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: primary
    location: us-central1
    nodeConfig:
    - machineType: e2-medium
      oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
      preemptible: true
      serviceAccount: ${google_service_account.default.email}
    nodeCount: 1

---

